language: elixir
script:
  - MIX_ENV=test mix compile --force --warnings-as-errors
  - wget https://github.com/elixir-lsp/dialyzer_plts/releases/download/test-erlang-23.0.2_elixir-1.10.3/dialyxir_erlang-23.0_elixir-1.10.3.plt -O $HOME/.mix/dialyxir_erlang-23.0_elixir-1.10.3.plt
  - wget https://github.com/elixir-lsp/dialyzer_plts/releases/download/test-erlang-23.0.2_elixir-1.10.3/elixir-ls-23.0.3_elixir-1.10.3 -O $HOME/.mix/elixir-ls-23.0.3_elixir-1.10.3
  - cp $HOME/.mix/elixir-ls-23.0.3_elixir-1.10.3 $HOME/.mix/elixir-ls-23.0.3_elixir-1.10.3.plt
  - |
    if [[ "$CHECK_FORMATTED" -eq 1 ]]
    then
      mix format --check-formatted
    else
      echo "Not checking formatting"
    fi
  - mix test --trace
  - ls -l $HOME/.mix/
env:
  global:
    - MIX_HOME=$HOME/.mix
cache:
  directories:
  - $HOME/.mix
  - deps
  - _build
matrix:
  include:
    - otp_release: 21.3
      elixir: 1.8.2
    - otp_release: 22.3
      elixir: 1.9.4
    - otp_release: 23.0.3
      elixir: 1.10.3
      env:
        - CHECK_FORMATTED=1
